### ISSUE TITLE
Drop frames when *.ass  contains lots of effects | 大量特效丢帧

### ISSUE THREAD

**Issue by RookieZoe** [subelf/Spp2Pgs#3]
First, Thank you very much for this repo. Very useful for me.

Here is the problem:
When the "*.ass" contains lots of effects, the "*.sup subtitle will drop frames.

And it seems that the recent release has been more than two years ago. I wonder if it will be update?

----------
首先，非常感谢这个项目，对我来说很有用。
不过看最近发布已经是两年多以前的了，不知道还会不会更新？
然后就是当 ass 字幕里面包含大量特效的时候，这时候生成的 sup 字幕会丢帧。
不知道能不能解决。我不会cpp，所以看源码比较吃力。。。

**Comment by RookieZoe** [comment]
OK, I know, Just turn off the strict mode with param "-x0". My bad.

Thanks again for this repo!

---

命令追加参数 -x0，把严格模式关掉就行了。
再次感谢！

**Comment by subelf** [comment]
这个项目的-x0命令行开关没有那么大的效果，只是解决个别情况下的小问题，而非放行所有特效。这个项目完全是在严格条件下进行sup文件生成的，目标是生成的sup文件可以在BD Scenarist之类的软件内使用。所以特效方面，即使继续开发，也不可能完全解决问题。理论上倒还是可能再优化一下，让丢帧丢得更均匀一些。
